name: Android Deploy

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  deploy-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Generate Gradle Wrapper
        run: |
          chmod +x gradlew

      - name: Install bundle
        run: |
          gem install bundler
          bundle install

      - name: Distribute app to Alpha track 🚀
        run: |
          bundle exec fastlane alpha

      - name: Upload APK to Github
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: release.apk
          asset_content_type: application/zip
